name: Run the Action on each commit
on:
  push:
    branches:
      - main
jobs:
  Raise_Pull_Request:
    runs-on: ubuntu-latest
    steps:
    - name: Display the path
      shell: bash
      run: |
       curl -L \
       -X POST \ -H "Accept: application/vnd.github+json" \
       -H "Authorization: Bearer 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>" \
       -H "X-GitHub-Api-Version: 2022-11-28" \ https://api.github.com/repos/OWNER/REPO/pulls \ -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"octocat:new-feature","base":"master"}'
