name: Run the Action on each commit
on:
  push:
    branches:
      - main
jobs:
  Raise_Pull_Request:
    runs-on: ubuntu-latest
    steps:
      - name: Open PR
        id: open_pr
        uses: rematocorp/open-pull-request-action@v1
        with:
          github-token: ${{ secrets.TOKEN }}
          from-branch: change_this
          to-branch: change_this
          repository-owner: change_this
          repository: change_this
